# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20160816_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
