# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_account_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
    ]
